/*
 * This file is generated by jOOQ.
 */
package alvin.study.springboot.jooq.infra.model.public_;


import alvin.study.springboot.jooq.infra.model.public_.tables.DepartmentEmployee;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IX_DEPARTMENT_EMPLOYEE_DEPARTMENT_ID = Internal.createIndex(DSL.name("IX_DEPARTMENT_EMPLOYEE_DEPARTMENT_ID"), DepartmentEmployee.DEPARTMENT_EMPLOYEE, new OrderField[] { DepartmentEmployee.DEPARTMENT_EMPLOYEE.ORG_ID, DepartmentEmployee.DEPARTMENT_EMPLOYEE.DEPARTMENT_ID }, false);
    public static final Index IX_DEPARTMENT_EMPLOYEE_EMPLOYEE_ID = Internal.createIndex(DSL.name("IX_DEPARTMENT_EMPLOYEE_EMPLOYEE_ID"), DepartmentEmployee.DEPARTMENT_EMPLOYEE, new OrderField[] { DepartmentEmployee.DEPARTMENT_EMPLOYEE.ORG_ID, DepartmentEmployee.DEPARTMENT_EMPLOYEE.EMPLOYEE_ID }, false);
}
