/*
 * This file is generated by jOOQ.
 */
package alvin.study.springboot.jooq.infra.model.public_;


import alvin.study.springboot.jooq.infra.model.DefaultCatalog;
import alvin.study.springboot.jooq.infra.model.public_.tables.Department;
import alvin.study.springboot.jooq.infra.model.public_.tables.DepartmentEmployee;
import alvin.study.springboot.jooq.infra.model.public_.tables.Employee;
import alvin.study.springboot.jooq.infra.model.public_.tables.Org;
import alvin.study.springboot.jooq.infra.model.public_.tables.User;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.DEPARTMENT</code>.
     */
    public final Department DEPARTMENT = Department.DEPARTMENT;

    /**
     * The table <code>PUBLIC.DEPARTMENT_EMPLOYEE</code>.
     */
    public final DepartmentEmployee DEPARTMENT_EMPLOYEE = DepartmentEmployee.DEPARTMENT_EMPLOYEE;

    /**
     * The table <code>PUBLIC.EMPLOYEE</code>.
     */
    public final Employee EMPLOYEE = Employee.EMPLOYEE;

    /**
     * The table <code>PUBLIC.ORG</code>.
     */
    public final Org ORG = Org.ORG;

    /**
     * The table <code>PUBLIC.USER</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Department.DEPARTMENT,
            DepartmentEmployee.DEPARTMENT_EMPLOYEE,
            Employee.EMPLOYEE,
            Org.ORG,
            User.USER
        );
    }
}
