/*
 * This file is generated by jOOQ.
 */
package alvin.study.springboot.jooq.infra.model.public_;


import alvin.study.springboot.jooq.infra.model.public_.tables.Department;
import alvin.study.springboot.jooq.infra.model.public_.tables.DepartmentEmployee;
import alvin.study.springboot.jooq.infra.model.public_.tables.Employee;
import alvin.study.springboot.jooq.infra.model.public_.tables.Org;
import alvin.study.springboot.jooq.infra.model.public_.tables.User;


/**
 * Convenience access to all tables in PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>PUBLIC.DEPARTMENT</code>.
     */
    public static final Department DEPARTMENT = Department.DEPARTMENT;

    /**
     * The table <code>PUBLIC.DEPARTMENT_EMPLOYEE</code>.
     */
    public static final DepartmentEmployee DEPARTMENT_EMPLOYEE = DepartmentEmployee.DEPARTMENT_EMPLOYEE;

    /**
     * The table <code>PUBLIC.EMPLOYEE</code>.
     */
    public static final Employee EMPLOYEE = Employee.EMPLOYEE;

    /**
     * The table <code>PUBLIC.ORG</code>.
     */
    public static final Org ORG = Org.ORG;

    /**
     * The table <code>PUBLIC.USER</code>.
     */
    public static final User USER = User.USER;
}
