/*
 * This file is generated by jOOQ.
 */
package alvin.study.springboot.jooq.infra.model.public_.tables.records;


import alvin.study.springboot.jooq.infra.model.public_.tables.DepartmentEmployee;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DepartmentEmployeeRecord extends UpdatableRecordImpl<DepartmentEmployeeRecord> implements Record9<Long, Long, Long, Long, Integer, Long, Long, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.DEPARTMENT_EMPLOYEE.ID</code>.
     */
    public DepartmentEmployeeRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.DEPARTMENT_EMPLOYEE.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.DEPARTMENT_EMPLOYEE.ORG_ID</code>.
     */
    public DepartmentEmployeeRecord setOrgId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.DEPARTMENT_EMPLOYEE.ORG_ID</code>.
     */
    public Long getOrgId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>PUBLIC.DEPARTMENT_EMPLOYEE.EMPLOYEE_ID</code>.
     */
    public DepartmentEmployeeRecord setEmployeeId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.DEPARTMENT_EMPLOYEE.EMPLOYEE_ID</code>.
     */
    public Long getEmployeeId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>PUBLIC.DEPARTMENT_EMPLOYEE.DEPARTMENT_ID</code>.
     */
    public DepartmentEmployeeRecord setDepartmentId(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.DEPARTMENT_EMPLOYEE.DEPARTMENT_ID</code>.
     */
    public Long getDepartmentId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>PUBLIC.DEPARTMENT_EMPLOYEE.VERSION</code>.
     */
    public DepartmentEmployeeRecord setVersion(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.DEPARTMENT_EMPLOYEE.VERSION</code>.
     */
    public Integer getVersion() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>PUBLIC.DEPARTMENT_EMPLOYEE.CREATED_BY</code>.
     */
    public DepartmentEmployeeRecord setCreatedBy(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.DEPARTMENT_EMPLOYEE.CREATED_BY</code>.
     */
    public Long getCreatedBy() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>PUBLIC.DEPARTMENT_EMPLOYEE.UPDATED_BY</code>.
     */
    public DepartmentEmployeeRecord setUpdatedBy(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.DEPARTMENT_EMPLOYEE.UPDATED_BY</code>.
     */
    public Long getUpdatedBy() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>PUBLIC.DEPARTMENT_EMPLOYEE.CREATED_AT</code>.
     */
    public DepartmentEmployeeRecord setCreatedAt(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.DEPARTMENT_EMPLOYEE.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>PUBLIC.DEPARTMENT_EMPLOYEE.UPDATED_AT</code>.
     */
    public DepartmentEmployeeRecord setUpdatedAt(LocalDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.DEPARTMENT_EMPLOYEE.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, Long, Long, Long, Integer, Long, Long, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, Long, Long, Long, Integer, Long, Long, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return DepartmentEmployee.DEPARTMENT_EMPLOYEE.ID;
    }

    @Override
    public Field<Long> field2() {
        return DepartmentEmployee.DEPARTMENT_EMPLOYEE.ORG_ID;
    }

    @Override
    public Field<Long> field3() {
        return DepartmentEmployee.DEPARTMENT_EMPLOYEE.EMPLOYEE_ID;
    }

    @Override
    public Field<Long> field4() {
        return DepartmentEmployee.DEPARTMENT_EMPLOYEE.DEPARTMENT_ID;
    }

    @Override
    public Field<Integer> field5() {
        return DepartmentEmployee.DEPARTMENT_EMPLOYEE.VERSION;
    }

    @Override
    public Field<Long> field6() {
        return DepartmentEmployee.DEPARTMENT_EMPLOYEE.CREATED_BY;
    }

    @Override
    public Field<Long> field7() {
        return DepartmentEmployee.DEPARTMENT_EMPLOYEE.UPDATED_BY;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return DepartmentEmployee.DEPARTMENT_EMPLOYEE.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return DepartmentEmployee.DEPARTMENT_EMPLOYEE.UPDATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getOrgId();
    }

    @Override
    public Long component3() {
        return getEmployeeId();
    }

    @Override
    public Long component4() {
        return getDepartmentId();
    }

    @Override
    public Integer component5() {
        return getVersion();
    }

    @Override
    public Long component6() {
        return getCreatedBy();
    }

    @Override
    public Long component7() {
        return getUpdatedBy();
    }

    @Override
    public LocalDateTime component8() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component9() {
        return getUpdatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getOrgId();
    }

    @Override
    public Long value3() {
        return getEmployeeId();
    }

    @Override
    public Long value4() {
        return getDepartmentId();
    }

    @Override
    public Integer value5() {
        return getVersion();
    }

    @Override
    public Long value6() {
        return getCreatedBy();
    }

    @Override
    public Long value7() {
        return getUpdatedBy();
    }

    @Override
    public LocalDateTime value8() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value9() {
        return getUpdatedAt();
    }

    @Override
    public DepartmentEmployeeRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public DepartmentEmployeeRecord value2(Long value) {
        setOrgId(value);
        return this;
    }

    @Override
    public DepartmentEmployeeRecord value3(Long value) {
        setEmployeeId(value);
        return this;
    }

    @Override
    public DepartmentEmployeeRecord value4(Long value) {
        setDepartmentId(value);
        return this;
    }

    @Override
    public DepartmentEmployeeRecord value5(Integer value) {
        setVersion(value);
        return this;
    }

    @Override
    public DepartmentEmployeeRecord value6(Long value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public DepartmentEmployeeRecord value7(Long value) {
        setUpdatedBy(value);
        return this;
    }

    @Override
    public DepartmentEmployeeRecord value8(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public DepartmentEmployeeRecord value9(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public DepartmentEmployeeRecord values(Long value1, Long value2, Long value3, Long value4, Integer value5, Long value6, Long value7, LocalDateTime value8, LocalDateTime value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DepartmentEmployeeRecord
     */
    public DepartmentEmployeeRecord() {
        super(DepartmentEmployee.DEPARTMENT_EMPLOYEE);
    }

    /**
     * Create a detached, initialised DepartmentEmployeeRecord
     */
    public DepartmentEmployeeRecord(Long id, Long orgId, Long employeeId, Long departmentId, Integer version, Long createdBy, Long updatedBy, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(DepartmentEmployee.DEPARTMENT_EMPLOYEE);

        setId(id);
        setOrgId(orgId);
        setEmployeeId(employeeId);
        setDepartmentId(departmentId);
        setVersion(version);
        setCreatedBy(createdBy);
        setUpdatedBy(updatedBy);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised DepartmentEmployeeRecord
     */
    public DepartmentEmployeeRecord(alvin.study.springboot.jooq.infra.model.public_.tables.pojos.DepartmentEmployee value) {
        super(DepartmentEmployee.DEPARTMENT_EMPLOYEE);

        if (value != null) {
            setId(value.getId());
            setOrgId(value.getOrgId());
            setEmployeeId(value.getEmployeeId());
            setDepartmentId(value.getDepartmentId());
            setVersion(value.getVersion());
            setCreatedBy(value.getCreatedBy());
            setUpdatedBy(value.getUpdatedBy());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetChangedOnNotNull();
        }
    }
}
