/*
 * This file is generated by jOOQ.
 */
package alvin.study.springboot.jooq.infra.model.public_.tables.records;


import alvin.study.springboot.jooq.infra.model.public_.tables.Department;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DepartmentRecord extends UpdatableRecordImpl<DepartmentRecord> implements Record9<Long, Long, String, Long, Long, Long, Long, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.DEPARTMENT.ID</code>.
     */
    public DepartmentRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.DEPARTMENT.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.DEPARTMENT.ORG_ID</code>.
     */
    public DepartmentRecord setOrgId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.DEPARTMENT.ORG_ID</code>.
     */
    public Long getOrgId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>PUBLIC.DEPARTMENT.NAME</code>.
     */
    public DepartmentRecord setName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.DEPARTMENT.NAME</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.DEPARTMENT.PARENT_ID</code>.
     */
    public DepartmentRecord setParentId(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.DEPARTMENT.PARENT_ID</code>.
     */
    public Long getParentId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>PUBLIC.DEPARTMENT.DELETED</code>.
     */
    public DepartmentRecord setDeleted(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.DEPARTMENT.DELETED</code>.
     */
    public Long getDeleted() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>PUBLIC.DEPARTMENT.CREATED_BY</code>.
     */
    public DepartmentRecord setCreatedBy(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.DEPARTMENT.CREATED_BY</code>.
     */
    public Long getCreatedBy() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>PUBLIC.DEPARTMENT.UPDATED_BY</code>.
     */
    public DepartmentRecord setUpdatedBy(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.DEPARTMENT.UPDATED_BY</code>.
     */
    public Long getUpdatedBy() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>PUBLIC.DEPARTMENT.CREATED_AT</code>.
     */
    public DepartmentRecord setCreatedAt(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.DEPARTMENT.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>PUBLIC.DEPARTMENT.UPDATED_AT</code>.
     */
    public DepartmentRecord setUpdatedAt(LocalDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.DEPARTMENT.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, Long, String, Long, Long, Long, Long, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, Long, String, Long, Long, Long, Long, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Department.DEPARTMENT.ID;
    }

    @Override
    public Field<Long> field2() {
        return Department.DEPARTMENT.ORG_ID;
    }

    @Override
    public Field<String> field3() {
        return Department.DEPARTMENT.NAME;
    }

    @Override
    public Field<Long> field4() {
        return Department.DEPARTMENT.PARENT_ID;
    }

    @Override
    public Field<Long> field5() {
        return Department.DEPARTMENT.DELETED;
    }

    @Override
    public Field<Long> field6() {
        return Department.DEPARTMENT.CREATED_BY;
    }

    @Override
    public Field<Long> field7() {
        return Department.DEPARTMENT.UPDATED_BY;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return Department.DEPARTMENT.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return Department.DEPARTMENT.UPDATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getOrgId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public Long component4() {
        return getParentId();
    }

    @Override
    public Long component5() {
        return getDeleted();
    }

    @Override
    public Long component6() {
        return getCreatedBy();
    }

    @Override
    public Long component7() {
        return getUpdatedBy();
    }

    @Override
    public LocalDateTime component8() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component9() {
        return getUpdatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getOrgId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public Long value4() {
        return getParentId();
    }

    @Override
    public Long value5() {
        return getDeleted();
    }

    @Override
    public Long value6() {
        return getCreatedBy();
    }

    @Override
    public Long value7() {
        return getUpdatedBy();
    }

    @Override
    public LocalDateTime value8() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value9() {
        return getUpdatedAt();
    }

    @Override
    public DepartmentRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public DepartmentRecord value2(Long value) {
        setOrgId(value);
        return this;
    }

    @Override
    public DepartmentRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public DepartmentRecord value4(Long value) {
        setParentId(value);
        return this;
    }

    @Override
    public DepartmentRecord value5(Long value) {
        setDeleted(value);
        return this;
    }

    @Override
    public DepartmentRecord value6(Long value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public DepartmentRecord value7(Long value) {
        setUpdatedBy(value);
        return this;
    }

    @Override
    public DepartmentRecord value8(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public DepartmentRecord value9(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public DepartmentRecord values(Long value1, Long value2, String value3, Long value4, Long value5, Long value6, Long value7, LocalDateTime value8, LocalDateTime value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DepartmentRecord
     */
    public DepartmentRecord() {
        super(Department.DEPARTMENT);
    }

    /**
     * Create a detached, initialised DepartmentRecord
     */
    public DepartmentRecord(Long id, Long orgId, String name, Long parentId, Long deleted, Long createdBy, Long updatedBy, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Department.DEPARTMENT);

        setId(id);
        setOrgId(orgId);
        setName(name);
        setParentId(parentId);
        setDeleted(deleted);
        setCreatedBy(createdBy);
        setUpdatedBy(updatedBy);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised DepartmentRecord
     */
    public DepartmentRecord(alvin.study.springboot.jooq.infra.model.public_.tables.pojos.Department value) {
        super(Department.DEPARTMENT);

        if (value != null) {
            setId(value.getId());
            setOrgId(value.getOrgId());
            setName(value.getName());
            setParentId(value.getParentId());
            setDeleted(value.getDeleted());
            setCreatedBy(value.getCreatedBy());
            setUpdatedBy(value.getUpdatedBy());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetChangedOnNotNull();
        }
    }
}
