/*
 * This file is generated by jOOQ.
 */
package alvin.study.springboot.jooq.infra.model.public_.tables.records;


import alvin.study.springboot.jooq.infra.model.EmployeeInfo;
import alvin.study.springboot.jooq.infra.model.public_.tables.Employee;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record11;
import org.jooq.Record2;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmployeeRecord extends UpdatableRecordImpl<EmployeeRecord> implements Record11<Long, Long, String, String, String, EmployeeInfo, Long, Long, Long, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.EMPLOYEE.ID</code>.
     */
    public EmployeeRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.EMPLOYEE.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.EMPLOYEE.ORG_ID</code>.
     */
    public EmployeeRecord setOrgId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.EMPLOYEE.ORG_ID</code>.
     */
    public Long getOrgId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>PUBLIC.EMPLOYEE.NAME</code>.
     */
    public EmployeeRecord setName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.EMPLOYEE.NAME</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.EMPLOYEE.EMAIL</code>.
     */
    public EmployeeRecord setEmail(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.EMPLOYEE.EMAIL</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.EMPLOYEE.TITLE</code>.
     */
    public EmployeeRecord setTitle(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.EMPLOYEE.TITLE</code>.
     */
    public String getTitle() {
        return (String) get(4);
    }

    /**
     * Setter for <code>PUBLIC.EMPLOYEE.INFO</code>.
     */
    public EmployeeRecord setInfo(EmployeeInfo value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.EMPLOYEE.INFO</code>.
     */
    public EmployeeInfo getInfo() {
        return (EmployeeInfo) get(5);
    }

    /**
     * Setter for <code>PUBLIC.EMPLOYEE.DELETED</code>.
     */
    public EmployeeRecord setDeleted(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.EMPLOYEE.DELETED</code>.
     */
    public Long getDeleted() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>PUBLIC.EMPLOYEE.CREATED_BY</code>.
     */
    public EmployeeRecord setCreatedBy(Long value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.EMPLOYEE.CREATED_BY</code>.
     */
    public Long getCreatedBy() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>PUBLIC.EMPLOYEE.UPDATED_BY</code>.
     */
    public EmployeeRecord setUpdatedBy(Long value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.EMPLOYEE.UPDATED_BY</code>.
     */
    public Long getUpdatedBy() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>PUBLIC.EMPLOYEE.CREATED_AT</code>.
     */
    public EmployeeRecord setCreatedAt(LocalDateTime value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.EMPLOYEE.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>PUBLIC.EMPLOYEE.UPDATED_AT</code>.
     */
    public EmployeeRecord setUpdatedAt(LocalDateTime value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.EMPLOYEE.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Long, Long, String, String, String, EmployeeInfo, Long, Long, Long, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Long, Long, String, String, String, EmployeeInfo, Long, Long, Long, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Employee.EMPLOYEE.ID;
    }

    @Override
    public Field<Long> field2() {
        return Employee.EMPLOYEE.ORG_ID;
    }

    @Override
    public Field<String> field3() {
        return Employee.EMPLOYEE.NAME;
    }

    @Override
    public Field<String> field4() {
        return Employee.EMPLOYEE.EMAIL;
    }

    @Override
    public Field<String> field5() {
        return Employee.EMPLOYEE.TITLE;
    }

    @Override
    public Field<EmployeeInfo> field6() {
        return Employee.EMPLOYEE.INFO;
    }

    @Override
    public Field<Long> field7() {
        return Employee.EMPLOYEE.DELETED;
    }

    @Override
    public Field<Long> field8() {
        return Employee.EMPLOYEE.CREATED_BY;
    }

    @Override
    public Field<Long> field9() {
        return Employee.EMPLOYEE.UPDATED_BY;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return Employee.EMPLOYEE.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return Employee.EMPLOYEE.UPDATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getOrgId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getEmail();
    }

    @Override
    public String component5() {
        return getTitle();
    }

    @Override
    public EmployeeInfo component6() {
        return getInfo();
    }

    @Override
    public Long component7() {
        return getDeleted();
    }

    @Override
    public Long component8() {
        return getCreatedBy();
    }

    @Override
    public Long component9() {
        return getUpdatedBy();
    }

    @Override
    public LocalDateTime component10() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component11() {
        return getUpdatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getOrgId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getEmail();
    }

    @Override
    public String value5() {
        return getTitle();
    }

    @Override
    public EmployeeInfo value6() {
        return getInfo();
    }

    @Override
    public Long value7() {
        return getDeleted();
    }

    @Override
    public Long value8() {
        return getCreatedBy();
    }

    @Override
    public Long value9() {
        return getUpdatedBy();
    }

    @Override
    public LocalDateTime value10() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value11() {
        return getUpdatedAt();
    }

    @Override
    public EmployeeRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public EmployeeRecord value2(Long value) {
        setOrgId(value);
        return this;
    }

    @Override
    public EmployeeRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public EmployeeRecord value4(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public EmployeeRecord value5(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public EmployeeRecord value6(EmployeeInfo value) {
        setInfo(value);
        return this;
    }

    @Override
    public EmployeeRecord value7(Long value) {
        setDeleted(value);
        return this;
    }

    @Override
    public EmployeeRecord value8(Long value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public EmployeeRecord value9(Long value) {
        setUpdatedBy(value);
        return this;
    }

    @Override
    public EmployeeRecord value10(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public EmployeeRecord value11(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public EmployeeRecord values(Long value1, Long value2, String value3, String value4, String value5, EmployeeInfo value6, Long value7, Long value8, Long value9, LocalDateTime value10, LocalDateTime value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmployeeRecord
     */
    public EmployeeRecord() {
        super(Employee.EMPLOYEE);
    }

    /**
     * Create a detached, initialised EmployeeRecord
     */
    public EmployeeRecord(Long id, Long orgId, String name, String email, String title, EmployeeInfo info, Long deleted, Long createdBy, Long updatedBy, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Employee.EMPLOYEE);

        setId(id);
        setOrgId(orgId);
        setName(name);
        setEmail(email);
        setTitle(title);
        setInfo(info);
        setDeleted(deleted);
        setCreatedBy(createdBy);
        setUpdatedBy(updatedBy);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
    }

    /**
     * Create a detached, initialised EmployeeRecord
     */
    public EmployeeRecord(alvin.study.springboot.jooq.infra.model.public_.tables.pojos.Employee value) {
        super(Employee.EMPLOYEE);

        if (value != null) {
            setId(value.getId());
            setOrgId(value.getOrgId());
            setName(value.getName());
            setEmail(value.getEmail());
            setTitle(value.getTitle());
            setInfo(value.getInfo());
            setDeleted(value.getDeleted());
            setCreatedBy(value.getCreatedBy());
            setUpdatedBy(value.getUpdatedBy());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
        }
    }
}
