/*
 * This file is generated by jOOQ.
 */
package alvin.study.springboot.jooq.infra.model.public_.tables.records;


import alvin.study.springboot.jooq.infra.model.public_.tables.Org;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrgRecord extends UpdatableRecordImpl<OrgRecord> implements Record5<Long, String, Long, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached OrgRecord
     */
    public OrgRecord() {
        super(Org.ORG);
    }

    /**
     * Create a detached, initialised OrgRecord
     */
    public OrgRecord(Long id, String name, Long deleted, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Org.ORG);

        setId(id);
        setName(name);
        setDeleted(deleted);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised OrgRecord
     */
    public OrgRecord(alvin.study.springboot.jooq.infra.model.public_.tables.pojos.Org value) {
        super(Org.ORG);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setDeleted(value.getDeleted());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetChangedOnNotNull();
        }
    }

    /**
     * Getter for <code>PUBLIC.ORG.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.ORG.ID</code>.
     */
    public OrgRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.ORG.NAME</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.ORG.NAME</code>.
     */
    public OrgRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.ORG.DELETED</code>.
     */
    public Long getDeleted() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>PUBLIC.ORG.DELETED</code>.
     */
    public OrgRecord setDeleted(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.ORG.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>PUBLIC.ORG.CREATED_AT</code>.
     */
    public OrgRecord setCreatedAt(LocalDateTime value) {
        set(3, value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>PUBLIC.ORG.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>PUBLIC.ORG.UPDATED_AT</code>.
     */
    public OrgRecord setUpdatedAt(LocalDateTime value) {
        set(4, value);
        return this;
    }

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    @Override
    public Row5<Long, String, Long, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, String, Long, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Org.ORG.ID;
    }

    @Override
    public Field<String> field2() {
        return Org.ORG.NAME;
    }

    @Override
    public Field<Long> field3() {
        return Org.ORG.DELETED;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Org.ORG.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Org.ORG.UPDATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Long component3() {
        return getDeleted();
    }

    @Override
    public LocalDateTime component4() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component5() {
        return getUpdatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Long value3() {
        return getDeleted();
    }

    @Override
    public LocalDateTime value4() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value5() {
        return getUpdatedAt();
    }

    @Override
    public OrgRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public OrgRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public OrgRecord value3(Long value) {
        setDeleted(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public OrgRecord value4(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public OrgRecord value5(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public OrgRecord values(Long value1, String value2, Long value3, LocalDateTime value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }
}
