/*
 * This file is generated by jOOQ.
 */
package alvin.study.springboot.jooq.infra.model.public_.tables.records;


import alvin.study.springboot.jooq.infra.model.UserType;
import alvin.study.springboot.jooq.infra.model.public_.tables.User;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Record2;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record10<Long, Long, String, String, UserType, Long, Long, Long, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.USER.ID</code>.
     */
    public UserRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.USER.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.USER.ORG_ID</code>.
     */
    public UserRecord setOrgId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.USER.ORG_ID</code>.
     */
    public Long getOrgId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>PUBLIC.USER.ACCOUNT</code>.
     */
    public UserRecord setAccount(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.USER.ACCOUNT</code>.
     */
    public String getAccount() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.USER.PASSWORD</code>.
     */
    public UserRecord setPassword(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.USER.PASSWORD</code>.
     */
    public String getPassword() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.USER.TYPE</code>.
     */
    public UserRecord setType(UserType value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.USER.TYPE</code>.
     */
    public UserType getType() {
        return (UserType) get(4);
    }

    /**
     * Setter for <code>PUBLIC.USER.DELETED</code>.
     */
    public UserRecord setDeleted(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.USER.DELETED</code>.
     */
    public Long getDeleted() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>PUBLIC.USER.CREATED_BY</code>.
     */
    public UserRecord setCreatedBy(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.USER.CREATED_BY</code>.
     */
    public Long getCreatedBy() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>PUBLIC.USER.UPDATED_BY</code>.
     */
    public UserRecord setUpdatedBy(Long value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.USER.UPDATED_BY</code>.
     */
    public Long getUpdatedBy() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>PUBLIC.USER.CREATED_AT</code>.
     */
    public UserRecord setCreatedAt(LocalDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.USER.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>PUBLIC.USER.UPDATED_AT</code>.
     */
    public UserRecord setUpdatedAt(LocalDateTime value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.USER.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, Long, String, String, UserType, Long, Long, Long, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Long, Long, String, String, UserType, Long, Long, Long, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return User.USER.ID;
    }

    @Override
    public Field<Long> field2() {
        return User.USER.ORG_ID;
    }

    @Override
    public Field<String> field3() {
        return User.USER.ACCOUNT;
    }

    @Override
    public Field<String> field4() {
        return User.USER.PASSWORD;
    }

    @Override
    public Field<UserType> field5() {
        return User.USER.TYPE;
    }

    @Override
    public Field<Long> field6() {
        return User.USER.DELETED;
    }

    @Override
    public Field<Long> field7() {
        return User.USER.CREATED_BY;
    }

    @Override
    public Field<Long> field8() {
        return User.USER.UPDATED_BY;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return User.USER.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return User.USER.UPDATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getOrgId();
    }

    @Override
    public String component3() {
        return getAccount();
    }

    @Override
    public String component4() {
        return getPassword();
    }

    @Override
    public UserType component5() {
        return getType();
    }

    @Override
    public Long component6() {
        return getDeleted();
    }

    @Override
    public Long component7() {
        return getCreatedBy();
    }

    @Override
    public Long component8() {
        return getUpdatedBy();
    }

    @Override
    public LocalDateTime component9() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component10() {
        return getUpdatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getOrgId();
    }

    @Override
    public String value3() {
        return getAccount();
    }

    @Override
    public String value4() {
        return getPassword();
    }

    @Override
    public UserType value5() {
        return getType();
    }

    @Override
    public Long value6() {
        return getDeleted();
    }

    @Override
    public Long value7() {
        return getCreatedBy();
    }

    @Override
    public Long value8() {
        return getUpdatedBy();
    }

    @Override
    public LocalDateTime value9() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value10() {
        return getUpdatedAt();
    }

    @Override
    public UserRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public UserRecord value2(Long value) {
        setOrgId(value);
        return this;
    }

    @Override
    public UserRecord value3(String value) {
        setAccount(value);
        return this;
    }

    @Override
    public UserRecord value4(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public UserRecord value5(UserType value) {
        setType(value);
        return this;
    }

    @Override
    public UserRecord value6(Long value) {
        setDeleted(value);
        return this;
    }

    @Override
    public UserRecord value7(Long value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public UserRecord value8(Long value) {
        setUpdatedBy(value);
        return this;
    }

    @Override
    public UserRecord value9(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public UserRecord value10(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public UserRecord values(Long value1, Long value2, String value3, String value4, UserType value5, Long value6, Long value7, Long value8, LocalDateTime value9, LocalDateTime value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(Long id, Long orgId, String account, String password, UserType type, Long deleted, Long createdBy, Long updatedBy, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(User.USER);

        setId(id);
        setOrgId(orgId);
        setAccount(account);
        setPassword(password);
        setType(type);
        setDeleted(deleted);
        setCreatedBy(createdBy);
        setUpdatedBy(updatedBy);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(alvin.study.springboot.jooq.infra.model.public_.tables.pojos.User value) {
        super(User.USER);

        if (value != null) {
            setId(value.getId());
            setOrgId(value.getOrgId());
            setAccount(value.getAccount());
            setPassword(value.getPassword());
            setType(value.getType());
            setDeleted(value.getDeleted());
            setCreatedBy(value.getCreatedBy());
            setUpdatedBy(value.getUpdatedBy());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
        }
    }
}
