/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class alvin_study_se_runtime_JNIDemo */

#ifndef _Included_alvin_study_se_runtime_JNIDemo
#define _Included_alvin_study_se_runtime_JNIDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     alvin_study_se_runtime_JNIDemo
 * Method:    itoa
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_alvin_study_se_runtime_JNIDemo_itoa(JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
