/*
 * This file is generated by jOOQ.
 */
package alvin.study.infra.model.public_.tables;


import alvin.study.infra.model.public_.Indexes;
import alvin.study.infra.model.public_.Keys;
import alvin.study.infra.model.public_.Public;
import alvin.study.infra.model.public_.tables.records.DepartmentEmployeeRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function9;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row9;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DepartmentEmployee extends TableImpl<DepartmentEmployeeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PUBLIC.DEPARTMENT_EMPLOYEE</code>
     */
    public static final DepartmentEmployee DEPARTMENT_EMPLOYEE = new DepartmentEmployee();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DepartmentEmployeeRecord> getRecordType() {
        return DepartmentEmployeeRecord.class;
    }

    /**
     * The column <code>PUBLIC.DEPARTMENT_EMPLOYEE.ID</code>.
     */
    public final TableField<DepartmentEmployeeRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>PUBLIC.DEPARTMENT_EMPLOYEE.ORG_ID</code>.
     */
    public final TableField<DepartmentEmployeeRecord, Long> ORG_ID = createField(DSL.name("ORG_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.DEPARTMENT_EMPLOYEE.EMPLOYEE_ID</code>.
     */
    public final TableField<DepartmentEmployeeRecord, Long> EMPLOYEE_ID = createField(DSL.name("EMPLOYEE_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.DEPARTMENT_EMPLOYEE.DEPARTMENT_ID</code>.
     */
    public final TableField<DepartmentEmployeeRecord, Long> DEPARTMENT_ID = createField(DSL.name("DEPARTMENT_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.DEPARTMENT_EMPLOYEE.VERSION</code>.
     */
    public final TableField<DepartmentEmployeeRecord, Integer> VERSION = createField(DSL.name("VERSION"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>PUBLIC.DEPARTMENT_EMPLOYEE.CREATED_BY</code>.
     */
    public final TableField<DepartmentEmployeeRecord, Long> CREATED_BY = createField(DSL.name("CREATED_BY"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>PUBLIC.DEPARTMENT_EMPLOYEE.UPDATED_BY</code>.
     */
    public final TableField<DepartmentEmployeeRecord, Long> UPDATED_BY = createField(DSL.name("UPDATED_BY"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>PUBLIC.DEPARTMENT_EMPLOYEE.CREATED_AT</code>.
     */
    public final TableField<DepartmentEmployeeRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>PUBLIC.DEPARTMENT_EMPLOYEE.UPDATED_AT</code>.
     */
    public final TableField<DepartmentEmployeeRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    private DepartmentEmployee(Name alias, Table<DepartmentEmployeeRecord> aliased) {
        this(alias, aliased, null);
    }

    private DepartmentEmployee(Name alias, Table<DepartmentEmployeeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>PUBLIC.DEPARTMENT_EMPLOYEE</code> table reference
     */
    public DepartmentEmployee(String alias) {
        this(DSL.name(alias), DEPARTMENT_EMPLOYEE);
    }

    /**
     * Create an aliased <code>PUBLIC.DEPARTMENT_EMPLOYEE</code> table reference
     */
    public DepartmentEmployee(Name alias) {
        this(alias, DEPARTMENT_EMPLOYEE);
    }

    /**
     * Create a <code>PUBLIC.DEPARTMENT_EMPLOYEE</code> table reference
     */
    public DepartmentEmployee() {
        this(DSL.name("DEPARTMENT_EMPLOYEE"), null);
    }

    public <O extends Record> DepartmentEmployee(Table<O> child, ForeignKey<O, DepartmentEmployeeRecord> key) {
        super(child, key, DEPARTMENT_EMPLOYEE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IX_DEPARTMENT_EMPLOYEE_DEPARTMENT_ID, Indexes.IX_DEPARTMENT_EMPLOYEE_EMPLOYEE_ID);
    }

    @Override
    public Identity<DepartmentEmployeeRecord, Long> getIdentity() {
        return (Identity<DepartmentEmployeeRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<DepartmentEmployeeRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_C;
    }

    @Override
    public List<UniqueKey<DepartmentEmployeeRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UX_DEPARTMENT_EMPLOYEE_ID);
    }

    @Override
    public DepartmentEmployee as(String alias) {
        return new DepartmentEmployee(DSL.name(alias), this);
    }

    @Override
    public DepartmentEmployee as(Name alias) {
        return new DepartmentEmployee(alias, this);
    }

    @Override
    public DepartmentEmployee as(Table<?> alias) {
        return new DepartmentEmployee(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DepartmentEmployee rename(String name) {
        return new DepartmentEmployee(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DepartmentEmployee rename(Name name) {
        return new DepartmentEmployee(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DepartmentEmployee rename(Table<?> name) {
        return new DepartmentEmployee(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, Long, Long, Long, Integer, Long, Long, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function9<? super Long, ? super Long, ? super Long, ? super Long, ? super Integer, ? super Long, ? super Long, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function9<? super Long, ? super Long, ? super Long, ? super Long, ? super Integer, ? super Long, ? super Long, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
