/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class alvin_study_misc_JNIPrint */

#ifndef _Included_alvin_study_misc_JNIPrint
#define _Included_alvin_study_misc_JNIPrint
#ifdef __cplusplus
extern "C" {
#endif
/**
 * Class:     alvin_study_misc_JNIPrint
 * Method:    print
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_alvin_study_misc_JNIPrint_print(JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
