#
# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.core
#
# 配置 SpringBoot
spring:
  application:
    name: study-springboot-mybatis

  # 配置数据源和 Hikari 连接池
  # 参考: https://github.com/brettwooldridge/HikariCP
  datasource:
    # 配置默认连接池
    hikari:
      pool-name: dev
      maximum-pool-size: 50
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 590000
      minimum-idle: 5
      connection-test-query: select 1
    # 配置默认数据源
    url: jdbc:h2:./.data/dev;MODE=MYSQL;NON_KEYWORDS=USER
    username: dev
    password: password

  flyway:
    locations: classpath:/migration
    baseline-on-migrate: true
    table: schema_version

  data:
    web:
      pageable:
        default-page-size: 2000
        max-page-size: 5000

# 配置 mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**.xml
  type-aliases-package: alvin.study.infra.entity
  global-config:
    banner: false
    enable-sql-runner: true # 启用 SqlRunner 对象
    # db-config:
    #   update-strategy: always  # 配置字段自动更新策略
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    auto-mapping-unknown-column-behavior: warning

# 应用程序设置
application:
  security:
    hash:
      algorithm: HmacSHA256
      key: ndE2jdZNFixH9G6Aidsfyf7lYT3PxW
  zone: UTC
