/*
 * This file is generated by jOOQ.
 */
package alvin.study.springboot.jooq.infra.model.public_.tables;


import alvin.study.springboot.jooq.infra.model.public_.Keys;
import alvin.study.springboot.jooq.infra.model.public_.Public;
import alvin.study.springboot.jooq.infra.model.public_.tables.records.OrgRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function5;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Org extends TableImpl<OrgRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PUBLIC.ORG</code>
     */
    public static final Org ORG = new Org();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrgRecord> getRecordType() {
        return OrgRecord.class;
    }

    /**
     * The column <code>PUBLIC.ORG.ID</code>.
     */
    public final TableField<OrgRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>PUBLIC.ORG.NAME</code>.
     */
    public final TableField<OrgRecord, String> NAME = createField(DSL.name("NAME"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.ORG.DELETED</code>.
     */
    public final TableField<OrgRecord, Long> DELETED = createField(DSL.name("DELETED"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>PUBLIC.ORG.CREATED_AT</code>.
     */
    public final TableField<OrgRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>PUBLIC.ORG.UPDATED_AT</code>.
     */
    public final TableField<OrgRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private Org(Name alias, Table<OrgRecord> aliased) {
        this(alias, aliased, null);
    }

    private Org(Name alias, Table<OrgRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>PUBLIC.ORG</code> table reference
     */
    public Org(String alias) {
        this(DSL.name(alias), ORG);
    }

    /**
     * Create an aliased <code>PUBLIC.ORG</code> table reference
     */
    public Org(Name alias) {
        this(alias, ORG);
    }

    /**
     * Create a <code>PUBLIC.ORG</code> table reference
     */
    public Org() {
        this(DSL.name("ORG"), null);
    }

    public <O extends Record> Org(Table<O> child, ForeignKey<O, OrgRecord> key) {
        super(child, key, ORG);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<OrgRecord, Long> getIdentity() {
        return (Identity<OrgRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<OrgRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_1;
    }

    @Override
    public List<UniqueKey<OrgRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.IX_ORG_NAME);
    }

    @Override
    public Org as(String alias) {
        return new Org(DSL.name(alias), this);
    }

    @Override
    public Org as(Name alias) {
        return new Org(alias, this);
    }

    @Override
    public Org as(Table<?> alias) {
        return new Org(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Org rename(String name) {
        return new Org(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Org rename(Name name) {
        return new Org(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Org rename(Table<?> name) {
        return new Org(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, String, Long, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function5<? super Long, ? super String, ? super Long, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function5<? super Long, ? super String, ? super Long, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
