/*
 * This file is generated by jOOQ.
 */
package alvin.study.springboot.jooq.infra.model.public_.tables;


import alvin.study.springboot.jooq.infra.model.public_.Keys;
import alvin.study.springboot.jooq.infra.model.public_.Public;
import alvin.study.springboot.jooq.infra.model.public_.tables.records.OrgRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Org extends TableImpl<OrgRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PUBLIC.ORG</code>
     */
    public static final Org ORG = new Org();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrgRecord> getRecordType() {
        return OrgRecord.class;
    }

    /**
     * The column <code>PUBLIC.ORG.ID</code>.
     */
    public final TableField<OrgRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>PUBLIC.ORG.NAME</code>.
     */
    public final TableField<OrgRecord, String> NAME = createField(DSL.name("NAME"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.ORG.DELETED</code>.
     */
    public final TableField<OrgRecord, Long> DELETED = createField(DSL.name("DELETED"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>PUBLIC.ORG.CREATED_AT</code>.
     */
    public final TableField<OrgRecord, LocalDateTime> CREATED_AT = createField(DSL.name("CREATED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>PUBLIC.ORG.UPDATED_AT</code>.
     */
    public final TableField<OrgRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("UPDATED_AT"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    private Org(Name alias, Table<OrgRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Org(Name alias, Table<OrgRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>PUBLIC.ORG</code> table reference
     */
    public Org(String alias) {
        this(DSL.name(alias), ORG);
    }

    /**
     * Create an aliased <code>PUBLIC.ORG</code> table reference
     */
    public Org(Name alias) {
        this(alias, ORG);
    }

    /**
     * Create a <code>PUBLIC.ORG</code> table reference
     */
    public Org() {
        this(DSL.name("ORG"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<OrgRecord, Long> getIdentity() {
        return (Identity<OrgRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<OrgRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_1;
    }

    @Override
    public List<UniqueKey<OrgRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.IX_ORG_NAME);
    }

    @Override
    public Org as(String alias) {
        return new Org(DSL.name(alias), this);
    }

    @Override
    public Org as(Name alias) {
        return new Org(alias, this);
    }

    @Override
    public Org as(Table<?> alias) {
        return new Org(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Org rename(String name) {
        return new Org(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Org rename(Name name) {
        return new Org(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Org rename(Table<?> name) {
        return new Org(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Org where(Condition condition) {
        return new Org(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Org where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Org where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Org where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Org where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Org where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Org where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Org where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Org whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Org whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
