spring:
  application:
    name: study-springboot-multi-datasource

  main:
    banner-mode: off

  datasource:
    # 配置多数据源
    # 注意, 多数据源配置的方式和默认数据源略有不同
    db1:
      type: com.zaxxer.hikari.HikariDataSource
      jdbc-url: jdbc:h2:./.data/dev1;MODE=MYSQL;NON_KEYWORDS=USER
      username: dev
      password: password
      pool-name: dev1
      maximum-pool-size: 50
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 590000
      minimum-idle: 5
      connection-test-query: select 1
    db2:
      type: com.zaxxer.hikari.HikariDataSource
      jdbc-url: jdbc:h2:./.data/dev2;MODE=MYSQL;NON_KEYWORDS=USER
      username: dev
      password: password
      pool-name: dev2
      maximum-pool-size: 50
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 590000
      minimum-idle: 5
      connection-test-query: select 1

  # 对于多数据源, 需要禁用自动运行 flyway, 参考 alvin.study.core.flyway.Migration 类手动执行
  flyway:
    enabled: false

# 应用程序设置
application:
  zone: UTC
