/*
 * This file is generated by jOOQ.
 */
package alvin.study.springboot.jooq.infra.model.public_.tables.pojos;


import alvin.study.springboot.jooq.infra.model.EmployeeInfo;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Employee implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long orgId;
    private String name;
    private String email;
    private String title;
    private EmployeeInfo info;
    private Long deleted;
    private Long createdBy;
    private Long updatedBy;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public Employee() {}

    public Employee(Employee value) {
        this.id = value.id;
        this.orgId = value.orgId;
        this.name = value.name;
        this.email = value.email;
        this.title = value.title;
        this.info = value.info;
        this.deleted = value.deleted;
        this.createdBy = value.createdBy;
        this.updatedBy = value.updatedBy;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public Employee(
        Long id,
        Long orgId,
        String name,
        String email,
        String title,
        EmployeeInfo info,
        Long deleted,
        Long createdBy,
        Long updatedBy,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
    ) {
        this.id = id;
        this.orgId = orgId;
        this.name = name;
        this.email = email;
        this.title = title;
        this.info = info;
        this.deleted = deleted;
        this.createdBy = createdBy;
        this.updatedBy = updatedBy;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>PUBLIC.EMPLOYEE.ID</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>PUBLIC.EMPLOYEE.ID</code>.
     */
    public Employee setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>PUBLIC.EMPLOYEE.ORG_ID</code>.
     */
    public Long getOrgId() {
        return this.orgId;
    }

    /**
     * Setter for <code>PUBLIC.EMPLOYEE.ORG_ID</code>.
     */
    public Employee setOrgId(Long orgId) {
        this.orgId = orgId;
        return this;
    }

    /**
     * Getter for <code>PUBLIC.EMPLOYEE.NAME</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>PUBLIC.EMPLOYEE.NAME</code>.
     */
    public Employee setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>PUBLIC.EMPLOYEE.EMAIL</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>PUBLIC.EMPLOYEE.EMAIL</code>.
     */
    public Employee setEmail(String email) {
        this.email = email;
        return this;
    }

    /**
     * Getter for <code>PUBLIC.EMPLOYEE.TITLE</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>PUBLIC.EMPLOYEE.TITLE</code>.
     */
    public Employee setTitle(String title) {
        this.title = title;
        return this;
    }

    /**
     * Getter for <code>PUBLIC.EMPLOYEE.INFO</code>.
     */
    public EmployeeInfo getInfo() {
        return this.info;
    }

    /**
     * Setter for <code>PUBLIC.EMPLOYEE.INFO</code>.
     */
    public Employee setInfo(EmployeeInfo info) {
        this.info = info;
        return this;
    }

    /**
     * Getter for <code>PUBLIC.EMPLOYEE.DELETED</code>.
     */
    public Long getDeleted() {
        return this.deleted;
    }

    /**
     * Setter for <code>PUBLIC.EMPLOYEE.DELETED</code>.
     */
    public Employee setDeleted(Long deleted) {
        this.deleted = deleted;
        return this;
    }

    /**
     * Getter for <code>PUBLIC.EMPLOYEE.CREATED_BY</code>.
     */
    public Long getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>PUBLIC.EMPLOYEE.CREATED_BY</code>.
     */
    public Employee setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * Getter for <code>PUBLIC.EMPLOYEE.UPDATED_BY</code>.
     */
    public Long getUpdatedBy() {
        return this.updatedBy;
    }

    /**
     * Setter for <code>PUBLIC.EMPLOYEE.UPDATED_BY</code>.
     */
    public Employee setUpdatedBy(Long updatedBy) {
        this.updatedBy = updatedBy;
        return this;
    }

    /**
     * Getter for <code>PUBLIC.EMPLOYEE.CREATED_AT</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>PUBLIC.EMPLOYEE.CREATED_AT</code>.
     */
    public Employee setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Getter for <code>PUBLIC.EMPLOYEE.UPDATED_AT</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>PUBLIC.EMPLOYEE.UPDATED_AT</code>.
     */
    public Employee setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Employee other = (Employee) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.orgId == null) {
            if (other.orgId != null)
                return false;
        }
        else if (!this.orgId.equals(other.orgId))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.email == null) {
            if (other.email != null)
                return false;
        }
        else if (!this.email.equals(other.email))
            return false;
        if (this.title == null) {
            if (other.title != null)
                return false;
        }
        else if (!this.title.equals(other.title))
            return false;
        if (this.info == null) {
            if (other.info != null)
                return false;
        }
        else if (!this.info.equals(other.info))
            return false;
        if (this.deleted == null) {
            if (other.deleted != null)
                return false;
        }
        else if (!this.deleted.equals(other.deleted))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.updatedBy == null) {
            if (other.updatedBy != null)
                return false;
        }
        else if (!this.updatedBy.equals(other.updatedBy))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.orgId == null) ? 0 : this.orgId.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.info == null) ? 0 : this.info.hashCode());
        result = prime * result + ((this.deleted == null) ? 0 : this.deleted.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.updatedBy == null) ? 0 : this.updatedBy.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Employee (");

        sb.append(id);
        sb.append(", ").append(orgId);
        sb.append(", ").append(name);
        sb.append(", ").append(email);
        sb.append(", ").append(title);
        sb.append(", ").append(info);
        sb.append(", ").append(deleted);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(updatedBy);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
