#
# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.core
#
# 配置 Spring Boot
spring:
  main:
    banner-mode: off

  application:
    name: study-springboot-security

  # 数据源配置
  datasource:
    # 配置 Hikari 数据库连接池
    # 参考: https://github.com/brettwooldridge/HikariCP
    hikari:
      maximum-pool-size: 50
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 590000
      minimum-idle: 5
      connection-test-query: select 1

    url: jdbc:h2:./.data/dev;MODE=MYSQL;NON_KEYWORDS=USER
    username: dev
    password: password

  data:
    # Redis 配置
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      timeout: 2000
      lettuce:
        pool:
          enabled: true
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0

  # DB Migration 配置
  flyway:
    locations: classpath:/migration
    baseline-on-migrate: true
    table: schema_version

# 服务容器 (Tomcat) 配置
server:
  tomcat:
    uri-encoding: UTF-8
    keep-alive-timeout: 30000
    max-keep-alive-requests: 10000
    connection-timeout: 5s
    threads:
      max: 256
      min-spare: 0
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  http2:
    enabled: true
  compression:
    enabled: true

# 配置 Mybatis-Plus
mybatis-plus:
  mapper-locations: classpath*:/mapper/**.xml
  type-aliases-package: alvin.study.infra.entity
  global-config:
    banner: false
    enable-sql-runner: true # 启用 SqlRunner 对象
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    auto-mapping-unknown-column-behavior: warning

# 应用程序设置
application:
  security:
    hash:
      algorithm: HmacSHA256
      key: ndE2jdZNFixH9G6Aidsfyf7lYT3PxW
    jwt:
      key: RKZBC62CfMp1Vyfo19K9RE1ZVREaLDFDUVsY7xnQaBMOtodSp7oBa0ZdMeGXa2D6
      aud: study.alvin
      jti: study.alvin.org
    session:
      period: PT2H
  zone: UTC
