/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class alvin_study_misc_JNIDemo */

#ifndef _Included_alvin_study_misc_JNIDemo
#define _Included_alvin_study_misc_JNIDemo
#ifdef __cplusplus
extern "C"
{
#endif

    /**
     * 实现 alvin.study.misc.JNIDemo#itoa 方法
     */
    JNIEXPORT
    jstring JNICALL Java_alvin_study_misc_JNIDemo_itoa(JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
